### ISSUE TITLE
Clean up old code

### ISSUE THREAD

**Issue by somebody1234** [ConorOBrien-Foxx/Attache#56]
It seems like some things like `@saved` are no longer used, it might be worth skimming over the source to look for unused variables/functions like this

**Comment by ConorOBrien-Foxx** [comment]
yeah. it'd be best to document the code while doing this too

**Comment by somebody1234** [comment]
### To Do list
- [ ] Always have space after comment character `#`
- [ ] `@saved` appears to be useless now
- [ ] `AtFunction.from` appears to only be used once, and it's nothing more than a rearrangement of `AtFunction.new`
- [ ] `AtError` appears to have been replaced with `AttacheError`, and errors appear to now be thrown, not returned
- [ ] Various bits of data and/or commented-out code
  - [ ] `AtState.rb#161,1222,1348-1352,1378-1382`
  - [ ] `AtClass.rb#78,122,160-162`
  - [ ] `attache.rb#233`
  - [ ] `gendoc.rb#117,259`
  - [ ] `lib.rb#803,830-31`
- [ ] That one `error "ReferenceError"`
- [ ] `AtLambda#call` appears to be indented one level too far
- [ ] `$FORMAT_STRING`, `tokenize.rb#61`, `$TOKENIZER`, `tokenize.rb$256`
- [ ] Make operator description comments consistent (in `$PRECEDENCE`), `tokenize.rb#75`
- [ ] Various `# TODO`s
- [ ] `##` at `AtState.rb#65`
- [ ] Make section header formatting consistent in `AtFunctions.rb` (`File I/O`, line 450)
- [ ] Make functions use `Enumerable` (`powerset`, combinations/permutations?)

**Comment by somebody1234** [comment]
Are you planning on using a documentation generator? If so, which one?

If not, are you planning to have a consistent format for the comments?

**Comment by ConorOBrien-Foxx** [comment]
I have only a document generator for the language's functions themselves, found in `gendoc.rb`. I'm not opposed to the idea.
